### ISSUE TITLE
[WSFE] Date control

### ISSUE THREAD

**Issue by ssaid** [OCA/l10n-argentina#43]
We should control the date of account.invoice when using AFIP WS, the main reason behind this improvement is that when a voucher is send to AFIP they check the date and don't allow to validate a voucher that have a date before the last validated by afip. It raises this error:

> Errores: El nÃºmero o fecha del comprobante no se corresponde con el prÃ³ximo a autorizar. Consultar metodo FECompUltimoAutorizado. (Err. 10016)

One way to implement this is before sending the data to afip, check whether the last voucher validated has a date after the voucher we are trying to validate and raise and exception to the user.

@sebastiken I could make a PR with this change.

**Comment by sebastiken** [comment]
@ssaid I think that we could speak in Spanish, because this is _l10n-argentina_.
Es verdad que faltan varias validaciones. Ahora lo que hace el _módulo_ es pasarle la _info_ a AFIP para que haga las validaciones. Pero en un alto porcentaje, si se hacen _validaciones previas_, estaríamos bajando mucho el tráfico con la _AFIP_.
Si querés hacer la modificación, será bienvenida. También podemos planificar un _milestone_ para diagramar varias _validaciones previas_ y evitar lo máximo posible el envío a _AFIP_ de información que no podrá ser validada.

**Comment by ssaid** [comment]
Perfecto, de ahora en más todo en castellano.
Estaría bueno lo del milestone que decís así metemos todas las validaciones allí.

**Comment by sebastiken** [comment]
@ssaid se creó el _Milestone_ [WSFE-validations](https://github.com/OCA/l10n-argentina/milestone/2).
Hay que ir cargando los _issues_ correspondientes. Nos podemos basar en el _manual de WSFE_ para cumplir con todas esas validaciones.
